package core

import (
	"fmt"
	"testing"
)

var address = "http://192.168.0.101:38888"

func TestNewClient(t *testing.T) {
	//SetDebug()
	SetTimeOut(5)
	c := NewClient(address)

	err, exist, idDir, info, data := c.GetDirInfo("/y", "", 0)
	fmt.Printf("%v,%v,%v,%#v,%v\n", err, exist, idDir, info, data)

	for k, v := range info.Entries {
		fmt.Println(k, v)
	}
}

func TestFilerClient_Upload(t *testing.T) {
	SetDebug()
	SetTimeOut(5)
	c := NewClient(address)

	data, err := c.Upload([]byte("1"), "xx.xx", "/0/1/2/3/4/5/6/7/8/9/10/11/12/14/1.xx")
	fmt.Println(data, err)

	err = c.DELETE("/0/1/2/3/4/5/6/7/8/9/10/11/12/14/1.xx")
	fmt.Println(err)
}

func TestFilerClient_Delete(t *testing.T) {
	SetDebug()
	SetTimeOut(5)
	c := NewClient(address)

	err := c.DELETE("/")
	fmt.Println(err)
}

var raw = `
askjhdddddddddddddddddddddddddddddddddddddddddddddddddddff
askjhddddddddddddddddddddddddddddddddddddddddddddddd
ddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffa
skjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhddddddddddddddddd
ddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddd
askjhdddddddddddddddddddddddddddddddddddddddddddddddddddff
askjhdddddddddddddddddddddddddddddddddddddddddddddddddddff
askjhdddddddddddddddddddddddddddddddddddddddddddddddddddff
askjhddddddddddddddddddddddddddddddddddddddddddddddd
ddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffa
skjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhddddddddddddddddd
ddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddd
askjhdddddddddddddddddddddddddddddddddddddddddddddddddddff
askjhdddddddddddddddddddddddddddddddddddddddddddddddddddff
askjhdddddddddddddddddddddddddddddddddddddddddddddddddddff
askjhddddddddddddddddddddddddddddddddddddddddddddddd
ddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffa
skjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhddddddddddddddddd
ddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddd
askjhdddddddddddddddddddddddddddddddddddddddddddddddddddff
askjhdddddddddddddddddddddddddddddddddddddddddddddddddddff
dddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffaskjhdddddddddddddddddddddddddddddddddddddddddddddddddddffvv
`

//go test  -v -test.run="UploadXX.*" -test.bench="UploadXX.*" -test.count=5 -test.benchtime=2s
func Benchmark_UploadXX(b *testing.B) {
	//SetDebug()
	SetTimeOut(5)
	c := NewClient(address)
	d := fmt.Sprintf("/1/%d.xx", b.N)
	c.Upload([]byte(raw), "xx.xx", d)
	//fmt.Println(data, err)
}
