version: '2'

services:
  weedmaster:
    container_name: "seaweed_master"
    restart: always
    image: seaweed:latest
    #image: chrislusf/seaweedfs # use a remote image
    #    build: . # build our container from the local Dockerfile
    ports:
    - 39333:9333
    command: 'master -mdir="/master"'
    networks:
      default:
        aliases:
        - seaweed_master
    volumes:
    - /storage/app/seaweed/master:/data
  weedvolume:
    container_name: "seaweed_volume"
    restart: always
    image: seaweed:latest
    #image: chrislusf/seaweedfs # use a remote image
    #    build: . # build our container from the local Dockerfile
    ports:
    - 38080:8080
    #    - 18080:18080
    command: 'volume -max=20 -mserver="weedmaster:9333" -port=8080 -dir="/data1"'
    depends_on:
    - weedmaster
    networks:
      default:
        aliases:
        - seaweed_volume
    volumes:
    - /storage/app/seaweed/v1:/data
  filer:
    container_name: "seaweed_filer"
    restart: always
    image: seaweed:latest
    #image: chrislusf/seaweedfs # use a remote image
    #    build: . # build our container from the local Dockerfile
    ports:
    - 38888:8888
    #    - 18888:18888
    command: 'filer -master="weedmaster:9333"'
    depends_on:
    - weedmaster
    - weedvolume
    networks:
      default:
        aliases:
        - seaweed_filer

    volumes:
      - /storage/app/seaweed/config:/etc/seaweedfs
