version: '2'

services:
  weedmaster:
    container_name: "seaweed_master"
    restart: always
    image: seaweed:latest
    ports:
      - 39333:9333
    command: 'master'
    networks:
      default:
        aliases:
          - seaweed_master
    volumes:
      - /storage/app/seaweed/master:/data
  weedvolume1:
    container_name: "seaweed_volume1"
    restart: always
    image: seaweed:latest
    #ports:
    #- 38080:8080
    #    - 18080:18080
    command: 'volume -max=20 -mserver="seaweed_master:9333" -port=8080'
    depends_on:
      - weedmaster
    networks:
      default:
        aliases:
          - seaweed_volume1
    volumes:
      - /storage/app/seaweed/volume1:/data
  weedvolume2:
    container_name: "seaweed_volume2"
    restart: always
    image: seaweed:latest
    #ports:
    #  - 38080:8080
    #    - 18080:18080
    command: 'volume -max=20 -mserver="seaweed_master:9333" -port=8080'
    depends_on:
      - weedmaster
    networks:
      default:
        aliases:
          - seaweed_volume2
    volumes:
      - /storage/app/seaweed/volume2:/data
  filer:
    container_name: "seaweed_filer"
    restart: always
    image: seaweed:latest
    ports:
      - 38888:8888
    #    - 18888:18888
    command: 'filer -master="seaweed_master:9333" -port=8888'
    depends_on:
      - weedmaster
      - weedvolume1
      - weedvolume2
    networks:
      default:
        aliases:
          - seaweed_filer
    volumes:
      - /storage/app/seaweed/filer:/leveldb
